webtalk_init -webtalk_dir C:/Users/mg/Desktop/ELE112/lab/lab_3/lab_3.sim/sim_1/behav/xsim/xsim.dir/lab_3_uut_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 15 15:56:26 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "81337ece-cd66-4d50-87e4-1d2a2f23faa1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "216d12cd14994d3db00df6d0d4d8865f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3912 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10000140050 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "9.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15404_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1512306691 -regid "" -xml C:/Users/mg/Desktop/ELE112/lab/lab_3/lab_3.sim/sim_1/behav/xsim/xsim.dir/lab_3_uut_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/mg/Desktop/ELE112/lab/lab_3/lab_3.sim/sim_1/behav/xsim/xsim.dir/lab_3_uut_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/mg/Desktop/ELE112/lab/lab_3/lab_3.sim/sim_1/behav/xsim/xsim.dir/lab_3_uut_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
